const express = require("express");
const kimlikKontrol = require("../middleware/kimlikKontrol");
const tenantKontrol = require("../middleware/tenantKontrol");
const { yetkiKontrol } = require("../middleware/yetkiKontrol");
const controller = require("../controllers/kullaniciYonetimController");
const router = express.Router();
router.use(kimlikKontrol, tenantKontrol, yetkiKontrol("tenant.users"));
router.get("/", controller.listele);
router.post("/", controller.olustur);
router.patch("/:id", controller.guncelle);
router.patch("/:id/yetkiler", controller.yetkiGuncelle);
router.post("/:id/sifre", controller.sifreBelirle);
module.exports = router;
