const mongoose = require("mongoose");
const IntegrationConnection = require("../models/IntegrationConnection");
const MarketplaceProductMapping = require("../models/MarketplaceProductMapping");
const EticaretSiparis = require("../models/EticaretSiparis");
const MarketplaceReturn = require("../models/MarketplaceReturn");
const MarketplaceFinanceTransaction = require("../models/MarketplaceFinanceTransaction");
const IncomingDocument = require("../models/IncomingDocument");
const IntegrationSyncJob = require("../models/IntegrationSyncJob");
const IntegrationErrorKaydi = require("../models/IntegrationError");
const MarketplaceCustomerQuestion = require("../models/MarketplaceCustomerQuestion");
const MarketplaceCategoryMapping = require("../models/MarketplaceCategoryMapping");
const Tedarikci = require("../models/Tedarikci");
const Masraf = require("../models/Masraf");
const Kasa = require("../models/Kasa");
const Banka = require("../models/Banka");
const ParaHareket = require("../models/ParaHareket");
const { sifrele } = require("../services/sifrelemeServisi");
const { marketplaceAdapter, credentialsOku } = require("../integrations/marketplace/adapterFactory");
const IdeaSoftAdapter = require("../integrations/marketplace/IdeaSoftAdapter");
const { geciciTokenOlustur, tokenDogrula } = require("../services/tokenServisi");
const { sirayaAl, ideasoftPilotTest } = require("../services/eticaretSyncServisi");
const { kaydet: auditKaydet } = require("../modules/platform/services/auditServisi");

const PROVIDERS = ["TRENDYOL", "HEPSIBURADA", "N11", "AMAZON_TR", "CICEKSEPETI", "PAZARAMA", "IDEASOFT", "CUSTOM", "EDOCUMENT_CUSTOM"];
const SYNC_TYPES = ["PRODUCT_PULL", "PRODUCT_PUSH", "STOCK_PUSH", "PRICE_PUSH", "ORDER_PULL", "RETURN_PULL", "INVOICE_PULL", "INVOICE_PUSH", "FINANCE_PULL", "CARGO_SYNC", "QUESTION_PULL"];
function tId(req) { const userTenant = String(req.user?.tenantId || ""), middlewareTenant = String(req.tenantId || ""); if (!userTenant || (middlewareTenant && userTenant !== middlewareTenant)) throw Object.assign(new Error("Tenant doğrulaması başarısız."), { status: 403 }); return new mongoose.Types.ObjectId(userTenant); }
function userId(req) { return req.currentUser?._id || req.kullanici?.kullaniciId || null; }
function text(value, max = 500) { return String(value || "").trim().slice(0, max); }
function objectId(value) { return mongoose.Types.ObjectId.isValid(String(value || "")); }
function tarihAraligi(query) { const now = new Date(), end = query.bitis ? new Date(`${query.bitis}T23:59:59.999+03:00`) : now, start = query.baslangic ? new Date(`${query.baslangic}T00:00:00+03:00`) : new Date(now.getFullYear(), now.getMonth(), 1); return { $gte: start, $lte: end }; }
function connectionPublic(item) { const value = item?.toObject ? item.toObject() : { ...item }; delete value.encryptedCredentials; value.credentials = "********"; return value; }
const IDEASOFT_AKN_TENANT_ID = "6a8dc53a3ff8c8a32ff9545b";
function ideasoftTenantKontrol(tenantId) {
    const current = String(tenantId || ""), allowed = String(process.env.IDEASOFT_AKN_TENANT_ID || IDEASOFT_AKN_TENANT_ID).trim();
    if (!mongoose.Types.ObjectId.isValid(current)) throw Object.assign(new Error("Tenant doğrulaması başarısız."), { status: 403 });
    // Doğrulanan AKN tenantı varsayılan rollout hedefidir; ortam değişkeni
    // yalnızca kontrollü deployment override'ı olarak kullanılır.
    if (!mongoose.Types.ObjectId.isValid(allowed) || current !== allowed) throw Object.assign(new Error("IdeaSoft entegrasyonu bu tenant için etkin değil."), { code: "INTEGRATION_NOT_CONFIGURED", status: 409 });
}
function ideasoftRedirectUri() { return `${String(process.env.PUBLIC_APP_URL || "https://www.benimmuhasebe.com").replace(/\/$/, "")}/api/tenant/eticaret/ideasoft/oauth/callback`; }
async function credentialsBirleştir(connection, incoming) { const current = connection.encryptedCredentials ? credentialsOku(connection) : {}; return { ...current, ...Object.fromEntries(Object.entries(incoming || {}).filter(([, value]) => value !== undefined && value !== "")) }; }
async function ideasoftTokenSakla(connection, credentials, tokenData) { const merged = { ...credentials, accessToken: tokenData.access_token, refreshToken: tokenData.refresh_token || credentials.refreshToken, tokenType: tokenData.token_type || "bearer", tokenExpiresAt: new Date(Date.now() + Math.max(60, Number(tokenData.expires_in || 86400)) * 1000).toISOString() }; await IntegrationConnection.updateOne({ _id: connection._id, tenantId: connection.tenantId }, { $set: { encryptedCredentials: sifrele(JSON.stringify(merged)) } }); return merged; }

async function dashboard(req, res, next) {
    try {
        const tenantId = tId(req), range = tarihAraligi(req.query), provider = text(req.query.provider, 30).toUpperCase(), ortak = { tenantId }, returnFilter = { tenantId }, financeFilter = { tenantId }, documentFilter = { tenantId };
        if (provider) { ortak.platform = provider; returnFilter.marketplace = provider; financeFilter.provider = provider; documentFilter.provider = provider; }
        const today = new Date(), todayStart = new Date(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}T00:00:00+03:00`), todayEnd = new Date(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}T23:59:59.999+03:00`);
        const [orders, returns, finance, documents, errors, connections, todayOrderCount] = await Promise.all([
            EticaretSiparis.find({ ...ortak, siparisTarihi: range }).select("durum toplam komisyonTutari kargoTutari platform").lean(),
            MarketplaceReturn.find({ ...returnFilter, returnDate: range }).lean(), MarketplaceFinanceTransaction.find({ ...financeFilter, transactionDate: range }).lean(),
            IncomingDocument.find({ ...documentFilter, issueDate: range }).select("invoiceType processingStatus").lean(), IntegrationErrorKaydi.countDocuments({ tenantId, status: { $in: ["OPEN", "RETRYING"] }, ...(provider ? { provider } : {}) }), IntegrationConnection.countDocuments({ tenantId, active: true }),
            EticaretSiparis.countDocuments({ ...ortak, siparisTarihi: { $gte: todayStart, $lte: todayEnd } })
        ]);
        const sum = (rows, fn) => rows.reduce((n, x) => n + Number(fn(x) || 0), 0), byType = type => sum(finance.filter(x => x.type === type), x => x.amount);
        const gross = byType("SALE") || sum(orders, x => x.toplam), refunds = Math.abs(byType("REFUND")), commission = Math.abs(byType("COMMISSION")), cargo = Math.abs(byType("CARGO")), service = Math.abs(byType("SERVICE_FEE")), advertising = Math.abs(byType("ADVERTISING")), other = Math.abs(byType("OTHER")) + Math.abs(byType("WITHHOLDING"));
        res.json({ basarili: true, configured: connections > 0, durum: connections ? "ACTIVE" : "ENTEGRASYON AYARLANMADI", cards: { bugunkuPazaryeriSiparisleri: todayOrderCount, bekleyenSiparis: orders.filter(x => x.durum === "ALINDI").length, hazirlananSiparis: orders.filter(x => x.durum === "ISLENIYOR").length, kargoyaVerilen: orders.filter(x => x.durum === "TAMAMLANDI").length, iadeIptal: returns.length + orders.filter(x => x.durum === "IPTAL").length, pazaryeriCirosu: gross, pazaryeriKomisyonlari: commission, kargoKesintileri: cargo, digerKesintiler: service + advertising + other, netHakedis: gross - refunds - commission - cargo - service - advertising - other, beklenenOdeme: sum(finance.filter(x => x.type === "PAYMENT" && x.reconciliationStatus !== "MATCHED"), x => x.amount), gelenEFatura: documents.length, islenmemisMasrafFaturasi: documents.filter(x => ["KOMISYON_FATURASI", "KARGO_FATURASI", "HIZMET_FATURASI"].includes(x.invoiceType) && x.processingStatus === "UNPROCESSED").length, gonderilemeyenEFatura: documents.filter(x => x.processingStatus === "ERROR").length, senkronizasyonHatasi: errors } });
    } catch (error) { next(error); }
}
async function connections(req, res, next) { try { const list = await IntegrationConnection.find({ tenantId: tId(req) }).sort({ active: -1, provider: 1, storeName: 1 }).lean(); res.json({ basarili: true, connections: list.map(connectionPublic) }); } catch (error) { next(error); } }
async function connectionCreate(req, res, next) {
    try {
        const body = req.body || {}, provider = text(body.provider, 30).toUpperCase(); if (!PROVIDERS.includes(provider) || !text(body.storeName)) return res.status(400).json({ basarili: false, mesaj: "Sağlayıcı ve mağaza adı zorunludur." });
        if (provider === "IDEASOFT") { ideasoftTenantKontrol(tId(req)); if (!text(body.apiBaseUrl) || !text(body.credentials?.clientId) || !text(body.credentials?.clientSecret)) return res.status(400).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "IdeaSoft mağaza domaini, Client ID ve Client Secret zorunludur." }); new IdeaSoftAdapter({ provider, apiBaseUrl: text(body.apiBaseUrl), active: true }, body.credentials); }
        if (!body.credentials || typeof body.credentials !== "object" || !Object.keys(body.credentials).length) return res.status(400).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "Entegrasyon bağlantı bilgileri zorunludur." });
        const connection = await IntegrationConnection.create({ tenantId: tId(req), type: body.type === "EDOCUMENT" ? "EDOCUMENT" : "MARKETPLACE", provider, storeName: text(body.storeName, 160), sellerId: text(body.sellerId, 160), merchantId: text(body.merchantId, 160), apiBaseUrl: provider === "IDEASOFT" ? text(body.apiBaseUrl, 300) : "", encryptedCredentials: sifrele(JSON.stringify(body.credentials)), environment: body.environment === "STAGE" ? "STAGE" : "PRODUCTION", active: body.active !== false, createdBy: userId(req) });
        await auditKaydet({ req, action: "ECOMMERCE_CONNECTION_CREATED", resource: "IntegrationConnection", resourceId: String(connection._id), details: { provider, storeName: connection.storeName } });
        res.status(201).json({ basarili: true, connection: connectionPublic(connection) });
    } catch (error) { next(error); }
}
async function connectionUpdate(req, res, next) {
    try {
        if (!objectId(req.params.id)) return res.status(400).json({ basarili: false, mesaj: "Geçersiz bağlantı." }); const body = req.body || {}, tenantId = tId(req), set = {}, existing = await IntegrationConnection.findOne({ _id: req.params.id, tenantId }).select("+encryptedCredentials"); if (!existing) return res.status(404).json({ basarili: false, mesaj: "Bağlantı bulunamadı." });
        if (existing.provider === "IDEASOFT") ideasoftTenantKontrol(tenantId);
        for (const key of ["storeName", "sellerId", "merchantId"]) if (body[key] !== undefined) set[key] = text(body[key], 160); if (body.apiBaseUrl !== undefined && existing.provider === "IDEASOFT") set.apiBaseUrl = text(body.apiBaseUrl, 300); if (body.environment !== undefined) set.environment = body.environment === "STAGE" ? "STAGE" : "PRODUCTION"; if (body.active !== undefined) set.active = Boolean(body.active); if (body.credentials && typeof body.credentials === "object" && Object.keys(body.credentials).length) set.encryptedCredentials = sifrele(JSON.stringify(await credentialsBirleştir(existing, body.credentials)));
        const connection = await IntegrationConnection.findOneAndUpdate({ _id: req.params.id, tenantId }, { $set: set }, { new: true, runValidators: true });
        await auditKaydet({ req, action: "ECOMMERCE_CONNECTION_UPDATED", resource: "IntegrationConnection", resourceId: String(connection._id), details: { changedFields: Object.keys(set).filter(x => x !== "encryptedCredentials"), credentialsChanged: Boolean(set.encryptedCredentials) } });
        res.json({ basarili: true, connection: connectionPublic(connection) });
    } catch (error) { next(error); }
}
async function connectionDisable(req, res, next) { try { const item = await IntegrationConnection.findOneAndUpdate({ _id: req.params.id, tenantId: tId(req) }, { $set: { active: false } }, { new: true }); if (!item) return res.status(404).json({ basarili: false, mesaj: "Bağlantı bulunamadı." }); await auditKaydet({ req, action: "ECOMMERCE_CONNECTION_DISABLED", resource: "IntegrationConnection", resourceId: String(item._id) }); res.json({ basarili: true, connection: connectionPublic(item) }); } catch (error) { next(error); } }
async function connectionTest(req, res, next) { try { const tenantId = tId(req), connection = await IntegrationConnection.findOne({ _id: req.params.id, tenantId, active: true }).select("+encryptedCredentials"); if (!connection) return res.status(404).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "Aktif bağlantı bulunamadı." }); let adapter = marketplaceAdapter(connection); if (connection.provider === "IDEASOFT") { ideasoftTenantKontrol(tenantId); let credentials = credentialsOku(connection); if (!credentials.accessToken && credentials.refreshToken) { credentials = await ideasoftTokenSakla(connection, credentials, await adapter.refreshAccessToken()); adapter = new IdeaSoftAdapter(connection, credentials); } if (!credentials.accessToken) { const state = geciciTokenOlustur({ type: "IDEASOFT_OAUTH", tenantId: String(tenantId), connectionId: String(connection._id), userId: String(userId(req) || "") }), authorizationUrl = adapter.authorizationUrl({ redirectUri: ideasoftRedirectUri(), state }); return res.status(428).json({ basarili: false, kod: "OAUTH_AUTHORIZATION_REQUIRED", mesaj: "IdeaSoft mağaza yöneticisi yetkilendirmesi gerekli.", authorizationUrl, redirectUri: ideasoftRedirectUri() }); } }
        const result = await adapter.testConnection(); await IntegrationConnection.updateOne({ _id: connection._id, tenantId }, { $set: { lastSuccessfulSyncAt: new Date(), lastError: "" } }); res.json({ basarili: true, result }); } catch (error) { if (error.code) return res.status(error.status || 400).json({ basarili: false, kod: error.code, mesaj: error.message }); next(error); } }
async function ideasoftOauthCallback(req, res, next) {
    // Bu rota kimlikKontrol'den önce tanımlıdır (SameSite=Strict oturum çerezi IdeaSoft'un cross-site
    // yönlendirmesinde gönderilmez); güvenlik tamamen imzalı ve süreli state JWT'sinden gelir.
    try {
        const payload = tokenDogrula(text(req.query.state, 4000));
        if (payload.type !== "IDEASOFT_OAUTH" || !objectId(payload.tenantId) || !objectId(payload.userId) || !objectId(payload.connectionId)) return res.status(403).send("IdeaSoft yetkilendirme isteği doğrulanamadı.");
        const tenantId = new mongoose.Types.ObjectId(payload.tenantId);
        ideasoftTenantKontrol(tenantId);
        const connection = await IntegrationConnection.findOne({ _id: payload.connectionId, tenantId, provider: "IDEASOFT", active: true }).select("+encryptedCredentials");
        if (!connection) return res.status(409).send("IdeaSoft bağlantısı bulunamadı.");
        const credentials = credentialsOku(connection), adapter = new IdeaSoftAdapter(connection, credentials), tokens = await adapter.exchangeAuthorizationCode(text(req.query.code, 4000), ideasoftRedirectUri());
        await ideasoftTokenSakla(connection, credentials, tokens);
        await auditKaydet({ req, action: "IDEASOFT_OAUTH_CONNECTED", resource: "IntegrationConnection", resourceId: String(connection._id), tenantId, details: { provider: "IDEASOFT" } });
        return res.redirect(302, "/erp/?ideasoft=connected");
    } catch (error) {
        if (error.code) return res.redirect(302, `/erp/?ideasoft=error&code=${encodeURIComponent(error.code)}`);
        next(error);
    }
}
async function ideasoftPilot(req, res, next) { try { const tenantId = tId(req); ideasoftTenantKontrol(tenantId); const connection = await IntegrationConnection.findOne({ _id: req.params.id, tenantId, provider: "IDEASOFT", active: true }); if (!connection) return res.status(409).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "IdeaSoft bağlantısı bulunamadı." }); const result = await ideasoftPilotTest({ tenantId, connection, userId: userId(req) }); res.json({ basarili: result.status === "SUCCESS", result }); } catch (error) { if (error.code) return res.status(error.status || 400).json({ basarili: false, kod: error.code, mesaj: error.message }); next(error); } }
async function syncCreate(req, res, next) { try { const type = text(req.body?.type, 30).toUpperCase(), tenantId = tId(req); if (!SYNC_TYPES.includes(type) || !objectId(req.body?.connectionId)) return res.status(400).json({ basarili: false, mesaj: "Bağlantı ve geçerli senkronizasyon türü zorunludur." }); const connection = await IntegrationConnection.findOne({ _id: req.body.connectionId, tenantId, active: true }); if (!connection) return res.status(409).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "Entegrasyon ayarlanmadı." }); if (connection.provider === "IDEASOFT") { ideasoftTenantKontrol(tenantId); if (connection.pilotStatus !== "SUCCESS" && !["PRODUCT_PULL", "ORDER_PULL"].includes(type)) return res.status(409).json({ basarili: false, kod: "PILOT_TEST_REQUIRED", mesaj: "Stok ve fiyat gönderiminden önce IdeaSoft küçük testi başarıyla tamamlanmalıdır." }); } const job = await sirayaAl({ tenantId, connection, type, userId: userId(req), hemenCalistir: type === "ORDER_PULL" }); res.status(type === "ORDER_PULL" ? 200 : 202).json({ basarili: type !== "ORDER_PULL" || job.status !== "FAILED", mesaj: type === "ORDER_PULL" ? "IdeaSoft sipariş çekme işlemi tamamlandı." : "Senkronizasyon kuyruğa alındı.", job }); } catch (error) { if (error.code) return res.status(error.status || 400).json({ basarili: false, kod: error.code, mesaj: error.message }); next(error); } }
async function list(Model, key, req, res, next, dateField = "createdAt") { try { const filter = { tenantId: tId(req) }; if (req.query.baslangic || req.query.bitis) filter[dateField] = tarihAraligi(req.query); if (req.query.provider) { const providerField = Model === EticaretSiparis ? "platform" : Model === MarketplaceReturn ? "marketplace" : "provider"; filter[providerField] = text(req.query.provider, 30).toUpperCase(); } const rows = await Model.find(filter).select("-rawData -hamVeri -xmlFile -pdfFile -technicalDetails").sort({ [dateField]: -1 }).limit(500).lean(); res.json({ basarili: true, toplam: rows.length, [key]: rows }); } catch (error) { next(error); } }
const mappings = (req, res, next) => list(MarketplaceProductMapping, "mappings", req, res, next);
const returns = (req, res, next) => list(MarketplaceReturn, "returns", req, res, next, "returnDate");
const finance = (req, res, next) => list(MarketplaceFinanceTransaction, "transactions", req, res, next, "transactionDate");
const documents = (req, res, next) => list(IncomingDocument, "documents", req, res, next, "issueDate");
const syncJobs = (req, res, next) => list(IntegrationSyncJob, "jobs", req, res, next);
const errors = (req, res, next) => list(IntegrationErrorKaydi, "errors", req, res, next);
const questions = (req, res, next) => list(MarketplaceCustomerQuestion, "questions", req, res, next, "questionDate");
const categoryMappings = (req, res, next) => list(MarketplaceCategoryMapping, "categoryMappings", req, res, next);
async function mappingUpsert(req, res, next) { try { if (!objectId(req.params.productId) || !objectId(req.body?.storeConnectionId)) return res.status(400).json({ basarili: false, mesaj: "Ürün ve bağlantı zorunludur." }); const connection = await IntegrationConnection.findOne({ _id: req.body.storeConnectionId, tenantId: tId(req), active: true }); if (!connection) return res.status(404).json({ basarili: false, mesaj: "Bağlantı bulunamadı." }); const mapping = await MarketplaceProductMapping.findOneAndUpdate({ tenantId: tId(req), productId: req.params.productId, storeConnectionId: connection._id }, { $set: { provider: connection.provider, connectionId: connection._id, externalProductId: text(req.body.externalProductId), externalBarcode: text(req.body.externalBarcode), externalSku: text(req.body.externalSku), externalCategoryId: text(req.body.externalCategoryId), categoryAttributes: req.body.categoryAttributes || {}, safetyStock: Math.max(0, Number(req.body.safetyStock || 0)), syncStatus: "PENDING" } }, { upsert: true, new: true, runValidators: true }); res.json({ basarili: true, mapping }); } catch (error) { next(error); } }
async function categoryMappingUpsert(req, res, next) { try { if (!objectId(req.body?.connectionId) || !text(req.body?.erpCategory) || !text(req.body?.externalCategoryId)) return res.status(400).json({ basarili: false, mesaj: "Bağlantı, ERP kategorisi ve pazaryeri kategorisi zorunludur." }); const connection = await IntegrationConnection.findOne({ _id: req.body.connectionId, tenantId: tId(req), active: true }); if (!connection) return res.status(404).json({ basarili: false, mesaj: "Bağlantı bulunamadı." }); const mapping = await MarketplaceCategoryMapping.findOneAndUpdate({ tenantId: tId(req), connectionId: connection._id, erpCategory: text(req.body.erpCategory, 160) }, { $set: { provider: connection.provider, externalCategoryId: text(req.body.externalCategoryId, 160), externalCategoryName: text(req.body.externalCategoryName, 300), attributeMappings: req.body.attributeMappings || {}, status: "MAPPED", lastError: "" } }, { upsert: true, new: true, runValidators: true }); res.json({ basarili: true, mapping }); } catch (error) { next(error); } }
async function documentMatchSupplier(req, res, next) { try { const supplier = await Tedarikci.findOne({ _id: req.body?.supplierId, tenantId: tId(req) }); if (!supplier) return res.status(404).json({ basarili: false, mesaj: "Tedarikçi bulunamadı." }); const document = await IncomingDocument.findOneAndUpdate({ _id: req.params.id, tenantId: tId(req) }, { $set: { matchedSupplierId: supplier._id, processingStatus: "MATCHED" } }, { new: true }); if (!document) return res.status(404).json({ basarili: false, mesaj: "Belge bulunamadı." }); res.json({ basarili: true, document }); } catch (error) { next(error); } }
async function documentApproveExpense(req, res, next) {
    const tenantId = tId(req), body = req.body || {}; let account = null, expense = null, movement = null, Model;
    try {
        if (body.confirm !== true) return res.status(409).json({ basarili: false, kod: "USER_APPROVAL_REQUIRED", mesaj: "Masraf kaydı için kullanıcı onayı zorunludur." });
        const document = await IncomingDocument.findOne({ _id: req.params.id, tenantId, processingStatus: { $in: ["UNPROCESSED", "MATCHED", "APPROVAL_REQUIRED"] } }); if (!document) return res.status(409).json({ basarili: false, mesaj: "Belge bulunamadı veya daha önce işlendi." });
        Model = body.accountType === "BANKA" ? Banka : Kasa; account = await Model.findOneAndUpdate({ _id: body.accountId, tenantId, aktif: true, bakiye: { $gte: document.grandTotal } }, { $inc: { bakiye: -document.grandTotal } }, { new: true }); if (!account) return res.status(409).json({ basarili: false, mesaj: "Ödeme hesabı bulunamadı veya bakiye yetersiz." });
        const suggested = document.invoiceType === "KARGO_FATURASI" ? "KARGO" : document.invoiceType === "KOMISYON_FATURASI" ? "PAZARYERI_KOMISYON" : "DIGER", category = body.category || suggested;
        expense = await Masraf.create({ tenantId, tarih: document.issueDate, kategori: category, aciklama: `${document.senderTitle} · ${document.invoiceNo}`, tutar: document.grandTotal, firma: document.senderTitle, fisNo: document.invoiceNo, kdvTutari: document.taxTotal, hesapTipi: body.accountType === "BANKA" ? "BANKA" : "KASA", hesapId: account._id, paraBirimi: document.currency, odemeDurumu: "ODENDI", kaynak: "E_BELGE", kullaniciId: userId(req) });
        movement = await ParaHareket.create({ tenantId, hesapTipi: expense.hesapTipi, hesapId: account._id, tip: "CIKIS", tutar: expense.tutar, paraBirimi: expense.paraBirimi, aciklama: expense.aciklama, kaynak: "MASRAF", kaynakId: expense._id, belgeNo: expense.fisNo, tarih: document.issueDate, kullaniciId: userId(req) }); expense.paraHareketId = movement._id; await expense.save();
        const claimed = await IncomingDocument.findOneAndUpdate({ _id: document._id, tenantId, processingStatus: { $in: ["UNPROCESSED", "MATCHED", "APPROVAL_REQUIRED"] } }, { $set: { matchedExpenseId: expense._id, processingStatus: "PROCESSED" } }, { new: true }); if (!claimed) throw Object.assign(new Error("Belge eşzamanlı olarak işlendi."), { status: 409 });
        await auditKaydet({ req, action: "ECOMMERCE_DOCUMENT_EXPENSE_CREATED", resource: "IncomingDocument", resourceId: String(document._id), details: { expenseId: String(expense._id), total: expense.tutar } }); res.status(201).json({ basarili: true, document: claimed, expense });
    } catch (error) { if (movement?._id) await ParaHareket.deleteOne({ _id: movement._id, tenantId }).catch(() => {}); if (expense?._id) await Masraf.deleteOne({ _id: expense._id, tenantId }).catch(() => {}); if (account?._id && Model) await Model.updateOne({ _id: account._id, tenantId }, { $inc: { bakiye: Number(expense?.tutar || 0) } }).catch(() => {}); next(error); }
}
async function documentArchive(req, res, next) { try { const document = await IncomingDocument.findOneAndUpdate({ _id: req.params.id, tenantId: tId(req) }, { $set: { processingStatus: "ARCHIVED" } }, { new: true }); if (!document) return res.status(404).json({ basarili: false, mesaj: "Belge bulunamadı." }); res.json({ basarili: true, document }); } catch (error) { next(error); } }
async function documentFile(req, res, next) { try { const field = req.params.format === "xml" ? "xmlFile" : req.params.format === "pdf" ? "pdfFile" : ""; if (!field) return res.status(400).json({ basarili: false, mesaj: "Belge biçimi PDF veya XML olmalıdır." }); const document = await IncomingDocument.findOne({ _id: req.params.id, tenantId: tId(req) }).select(`+${field}`).lean(); if (!document || !document[field]) return res.status(404).json({ basarili: false, mesaj: "Belge dosyası bulunamadı." }); res.json({ basarili: true, format: req.params.format.toUpperCase(), content: document[field] }); } catch (error) { next(error); } }
async function financeMatch(req, res, next) { try { if (req.body?.confirm !== true) return res.status(409).json({ basarili: false, kod: "USER_APPROVAL_REQUIRED", mesaj: "Banka eşleştirmesi için kullanıcı onayı zorunludur." }); const transaction = await MarketplaceFinanceTransaction.findOne({ _id: req.params.id, tenantId: tId(req), reconciliationStatus: { $ne: "MATCHED" } }); if (!transaction) return res.status(404).json({ basarili: false, mesaj: "Eşleştirilecek finans hareketi bulunamadı." }); const movement = await ParaHareket.findOne({ _id: req.body.bankMovementId, tenantId: tId(req), hesapTipi: "BANKA", tip: "GIRIS" }); if (!movement) return res.status(404).json({ basarili: false, mesaj: "Banka giriş hareketi bulunamadı." }); if ((movement.paraBirimi || "TRY") !== (transaction.currency || "TRY") || Math.abs(Number(movement.tutar) - Math.abs(Number(transaction.amount))) > 0.01) return res.status(409).json({ basarili: false, mesaj: "Tutar veya para birimi eşleşmiyor." }); transaction.bankMovementId = movement._id; transaction.reconciliationStatus = "MATCHED"; transaction.matchedBy = userId(req); transaction.matchedAt = new Date(); await transaction.save(); await auditKaydet({ req, action: "ECOMMERCE_FINANCE_MATCHED", resource: "MarketplaceFinanceTransaction", resourceId: String(transaction._id), details: { bankMovementId: String(movement._id), amount: transaction.amount } }); res.json({ basarili: true, transaction }); } catch (error) { next(error); } }
async function errorRetry(req, res, next) { try { const item = await IntegrationErrorKaydi.findOne({ _id: req.params.id, tenantId: tId(req), status: { $in: ["OPEN", "RETRYING"] } }); if (!item) return res.status(404).json({ basarili: false, mesaj: "Açık hata kaydı bulunamadı." }); if (!item.retryable || !SYNC_TYPES.includes(item.operation)) return res.status(409).json({ basarili: false, mesaj: "Bu hata otomatik tekrar denemeye uygun değil." }); const connection = await IntegrationConnection.findOne({ _id: item.connectionId, tenantId: tId(req), active: true }); if (!connection) return res.status(409).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "Aktif bağlantı bulunamadı." }); item.status = "RETRYING"; item.attemptCount += 1; item.lastAttemptAt = new Date(); await item.save(); const job = await sirayaAl({ tenantId: tId(req), connection, type: item.operation, userId: userId(req) }); await auditKaydet({ req, action: "ECOMMERCE_MANUAL_RETRY", resource: "IntegrationError", resourceId: String(item._id), details: { jobId: String(job._id) } }); res.status(202).json({ basarili: true, job }); } catch (error) { next(error); } }
async function questionAnswer(req, res, next) { try { const answer = text(req.body?.answer, 2000); if (answer.length < 10) return res.status(400).json({ basarili: false, mesaj: "Cevap en az 10 karakter olmalıdır." }); const question = await MarketplaceCustomerQuestion.findOne({ _id: req.params.id, tenantId: tId(req), status: "WAITING_FOR_ANSWER" }); if (!question) return res.status(404).json({ basarili: false, mesaj: "Yanıt bekleyen soru bulunamadı." }); const connection = await IntegrationConnection.findOne({ _id: question.connectionId, tenantId: tId(req), active: true }).select("+encryptedCredentials"); if (!connection) return res.status(409).json({ basarili: false, kod: "INTEGRATION_NOT_CONFIGURED", mesaj: "Aktif bağlantı bulunamadı." }); await marketplaceAdapter(connection).answerCustomerQuestion(question.externalQuestionId, answer); question.answer = answer; question.answerDate = new Date(); question.status = "ANSWERED"; await question.save(); res.json({ basarili: true, question }); } catch (error) { if (error.code) return res.status(error.status || 400).json({ basarili: false, kod: error.code, mesaj: error.message }); next(error); } }
module.exports = { dashboard, connections, connectionCreate, connectionUpdate, connectionDisable, connectionTest, ideasoftOauthCallback, ideasoftPilot, syncCreate, mappings, returns, finance, documents, syncJobs, errors, questions, categoryMappings, mappingUpsert, categoryMappingUpsert, documentMatchSupplier, documentApproveExpense, documentArchive, documentFile, financeMatch, errorRetry, questionAnswer, connectionPublic, tarihAraligi, ideasoftTenantKontrol };
